---

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.1-node
        environment:
          BUNDLER_VERSION: 2.0.1
    steps:
      - checkout
      - run:
          name: budler v2をインストール
          command: |
            sudo gem update --system
            sudo gem uninstall bundler
            sudo rm /usr/local/bin/bundle
            sudo rm /usr/local/bin/bundler
            sudo gem install bundler
            gem install bundler 
      - run:
          name: 依存関係のインストール
          command: bundle install --path vendor/bundle
      - run:
          name: テスト実行
          command: bundle exec rspec