---

version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run:
          name: 依存関係のインストール
          command: bundle install --path vendor/bundle
      - run:
          name: テスト実行
          command: bundle exec rspec